### PR TITLE
fix sizeStyle

### PR DESCRIPTION
**Pull request by ingoclaro**

### CODE REVIEW

**Comment by sunkibaek** [comment]
@ingoclaro Would you please explain what problem this PR will solve? Thanks.

**Comment by ingoclaro** [comment]
Without the else sizestyle is always set to the same value, which doesn't work if you want a specific size.

**Comment by ingoclaro** [comment]
To clarify: without the else, then the image is always using flexGrow: 1, and not respecting the width property.

**Comment by ingoclaro** [comment]
ping

**Review by originerd — APPROVED** [review]
👍 Thanks!

**Pull request merged**
